name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Linux:
    uses: ./.github/workflows/build-linux.yml

  Windows:
    uses: ./.github/workflows/build-windows.yml

  macOS:
    uses: ./.github/workflows/build-macos.yml

  FreeBSD:
    uses: ./.github/workflows/build-freebsd.yml

  Haiku:
    uses: ./.github/workflows/build-haiku.yml

  Consoles:
    uses: ./.github/workflows/build-console.yml

  Other:
    uses: ./.github/workflows/build-other.yml
